#############################################################################
# Makefile for building: out/VideoTimeline
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  VideoTimeline.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile VideoTimeline.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/arm-linux-gnueabihf/qt6 -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimediaWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimedia -I/usr/include/arm-linux-gnueabihf/qt6/QtGui -I/usr/include/arm-linux-gnueabihf/qt6/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt6/QtCore -Iout/moc -I/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VideoTimeline1.0.0
DISTDIR = /home/batuhantrkgl/shower/out/obj/VideoTimeline1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) /usr/lib/arm-linux-gnueabihf/libQt6MultimediaWidgets.so /usr/lib/arm-linux-gnueabihf/libQt6Widgets.so /usr/lib/arm-linux-gnueabihf/libQt6Multimedia.so /usr/lib/arm-linux-gnueabihf/libQt6Gui.so /usr/lib/arm-linux-gnueabihf/libGLX.so /usr/lib/arm-linux-gnueabihf/libOpenGL.so /usr/lib/arm-linux-gnueabihf/libQt6Network.so /usr/lib/arm-linux-gnueabihf/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = out/obj/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		videowidget.cpp \
		timelinewidget.cpp \
		networkclient.cpp out/moc/moc_mainwindow.cpp \
		out/moc/moc_videowidget.cpp \
		out/moc/moc_timelinewidget.cpp \
		out/moc/moc_networkclient.cpp
OBJECTS       = out/obj/main.o \
		out/obj/mainwindow.o \
		out/obj/videowidget.o \
		out/obj/timelinewidget.o \
		out/obj/networkclient.o \
		out/obj/moc_mainwindow.o \
		out/obj/moc_videowidget.o \
		out/obj/moc_timelinewidget.o \
		out/obj/moc_networkclient.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/lex.prf \
		VideoTimeline.pro mainwindow.h \
		videowidget.h \
		timelinewidget.h \
		networkclient.h \
		md3colors.h main.cpp \
		mainwindow.cpp \
		videowidget.cpp \
		timelinewidget.cpp \
		networkclient.cpp
QMAKE_TARGET  = VideoTimeline
DESTDIR       = out/
TARGET        = out/VideoTimeline


first: all
####### Build rules

out/VideoTimeline:  $(OBJECTS)  
	@test -d out/ || mkdir -p out/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VideoTimeline.pro /usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/lex.prf \
		VideoTimeline.pro \
		/usr/lib/arm-linux-gnueabihf/libQt6MultimediaWidgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt6Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt6Multimedia.prl \
		/usr/lib/arm-linux-gnueabihf/libQt6Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt6Network.prl \
		/usr/lib/arm-linux-gnueabihf/libQt6Core.prl
	$(QMAKE) -o Makefile VideoTimeline.pro
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/sanitize.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/toolchain.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/default_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/file_copies.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/lex.prf:
VideoTimeline.pro:
/usr/lib/arm-linux-gnueabihf/libQt6MultimediaWidgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt6Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt6Multimedia.prl:
/usr/lib/arm-linux-gnueabihf/libQt6Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt6Network.prl:
/usr/lib/arm-linux-gnueabihf/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile VideoTimeline.pro

qmake_all: FORCE


all: Makefile out/VideoTimeline

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h videowidget.h timelinewidget.h networkclient.h md3colors.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp videowidget.cpp timelinewidget.cpp networkclient.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: out/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) out/moc/moc_predefs.h
out/moc/moc_predefs.h: /usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o out/moc/moc_predefs.h /usr/lib/arm-linux-gnueabihf/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: out/moc/moc_mainwindow.cpp out/moc/moc_videowidget.cpp out/moc/moc_timelinewidget.cpp out/moc/moc_networkclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) out/moc/moc_mainwindow.cpp out/moc/moc_videowidget.cpp out/moc/moc_timelinewidget.cpp out/moc/moc_networkclient.cpp
out/moc/moc_mainwindow.cpp: mainwindow.h \
		md3colors.h \
		networkclient.h \
		out/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/batuhantrkgl/shower/out/moc/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++ -I/home/batuhantrkgl/shower -I/usr/include/arm-linux-gnueabihf/qt6 -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimediaWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimedia -I/usr/include/arm-linux-gnueabihf/qt6/QtGui -I/usr/include/arm-linux-gnueabihf/qt6/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include mainwindow.h -o out/moc/moc_mainwindow.cpp

out/moc/moc_videowidget.cpp: videowidget.h \
		md3colors.h \
		networkclient.h \
		out/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/batuhantrkgl/shower/out/moc/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++ -I/home/batuhantrkgl/shower -I/usr/include/arm-linux-gnueabihf/qt6 -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimediaWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimedia -I/usr/include/arm-linux-gnueabihf/qt6/QtGui -I/usr/include/arm-linux-gnueabihf/qt6/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include videowidget.h -o out/moc/moc_videowidget.cpp

out/moc/moc_timelinewidget.cpp: timelinewidget.h \
		md3colors.h \
		networkclient.h \
		out/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/batuhantrkgl/shower/out/moc/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++ -I/home/batuhantrkgl/shower -I/usr/include/arm-linux-gnueabihf/qt6 -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimediaWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimedia -I/usr/include/arm-linux-gnueabihf/qt6/QtGui -I/usr/include/arm-linux-gnueabihf/qt6/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include timelinewidget.h -o out/moc/moc_timelinewidget.cpp

out/moc/moc_networkclient.cpp: networkclient.h \
		out/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/batuhantrkgl/shower/out/moc/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt6/mkspecs/linux-g++ -I/home/batuhantrkgl/shower -I/usr/include/arm-linux-gnueabihf/qt6 -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimediaWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt6/QtMultimedia -I/usr/include/arm-linux-gnueabihf/qt6/QtGui -I/usr/include/arm-linux-gnueabihf/qt6/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include networkclient.h -o out/moc/moc_networkclient.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

out/obj/main.o: main.cpp mainwindow.h \
		md3colors.h \
		networkclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/main.o main.cpp

out/obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		md3colors.h \
		networkclient.h \
		videowidget.h \
		timelinewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/mainwindow.o mainwindow.cpp

out/obj/videowidget.o: videowidget.cpp videowidget.h \
		md3colors.h \
		networkclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/videowidget.o videowidget.cpp

out/obj/timelinewidget.o: timelinewidget.cpp timelinewidget.h \
		md3colors.h \
		networkclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/timelinewidget.o timelinewidget.cpp

out/obj/networkclient.o: networkclient.cpp networkclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/networkclient.o networkclient.cpp

out/obj/moc_mainwindow.o: out/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_mainwindow.o out/moc/moc_mainwindow.cpp

out/obj/moc_videowidget.o: out/moc/moc_videowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_videowidget.o out/moc/moc_videowidget.cpp

out/obj/moc_timelinewidget.o: out/moc/moc_timelinewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_timelinewidget.o out/moc/moc_timelinewidget.cpp

out/obj/moc_networkclient.o: out/moc/moc_networkclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_networkclient.o out/moc/moc_networkclient.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

